name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Docker to use Minikube's Docker daemon
      shell: powershell
      run: |
        echo "Configuring Docker to use Minikube's Docker daemon..."
        & minikube -p minikube docker-env --shell=powershell | Invoke-Expression

    - name: Build Backend Docker Image
      run: |
        docker build -t i222539nuedupk/mern-backend:latest ./backend

    - name: Build Frontend Docker Image
      run: |
        docker build -t i222539nuedupk/mern-frontend:latest ./frontend

    - name: Login to Docker Hub
      shell: cmd
      run: |
        echo Pakistan@4756 | docker login -u i222539nuedupk --password-stdin

    - name: Push Backend Image to Docker Hub
      run: docker push i222539nuedupk/mern-backend:latest

    - name: Push Frontend Image to Docker Hub
      run: docker push i222539nuedupk/mern-frontend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yaml
